config/routes.rb
Ggb::Application.routes.draw do
  resources :goodbads

  devise_for :users
  root "pages#home"
  get "about" => "pages#about"
  

end

app/models/goodbad.rb
class Goodbad < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/goodbads_controller.rb
class GoodbadsController < ApplicationController
  before_action :set_goodbad, only: [:show, :edit, :update, :destroy]

  def index
    @goodbads = Goodbad.all
  end

  def show
  end

  def new
    @goodbad = Goodbad.new
  end

  def edit
  end

  def create
    @goodbad = Goodbad.new(goodbad_params)
    if @goodbad.save
      redirect_to @goodbad, notice: 'Goodbad was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @goodbad.update(goodbad_params)
      redirect_to @goodbad, notice: 'Goodbad was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @goodbad.destroy
      redirect_to goodbads_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goodbad
      @goodbad = Goodbad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goodbad_params
      params.require(:goodbad).permit(:goodbad)
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goodbads_helper.rb
module GoodbadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/goodbads/_form.html.erb
<%= form_for(@goodbad) do |f| %>
  <% if @goodbad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goodbad.errors.count, "error") %> prohibited this goodbad from being saved:</h2>

      <ul>
      <% @goodbad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :goodbad %><br>
    <%= f.text_field :goodbad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goodbads/edit.html.erb
<h1>Editing goodbad</h1>

<%= render 'form' %>

<%= link_to 'Show', @goodbad %> |
<%= link_to 'Back', goodbads_path %>

app/views/goodbads/index.html.erb
<%= link_to 'New Goodbad', new_goodbad_path, class: "btn btn-primary btn-lg" %>

<table class="table">
  <thead>
    <tr>
      <th>Goodbad</th>
      <th>Time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @goodbads.each do |goodbad| %>
      <tr>
        <td><%= goodbad.goodbad %></td>
        <td><%= goodbad.created_at.strftime("%d %b %y") %></td>
        <td><%= link_to 'Show', goodbad %></td>
        <td><%= link_to 'Edit', edit_goodbad_path(goodbad) %></td>
        <td><%= link_to 'Destroy', goodbad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goodbad', new_goodbad_path %>

app/views/goodbads/new.html.erb
<h1>New goodbad</h1>

<%= render 'form' %>

<%= link_to 'Back', goodbads_path %>

app/views/goodbads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Goodbad:</strong>
  <%= @goodbad.goodbad %>
</p>

<%= link_to 'Edit', edit_goodbad_path(@goodbad) %> |
<%= link_to 'Back', goodbads_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Good, Good, Bad", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %> </li>
        <li><%= link_to "About", about_path %> </li>
        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete%> </li>
        <% else %>
            <li><%= link_to "Sign in", new_user_session_path %> </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Ggb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<div class="jumbotron">
	
	<% if user_signed_in? %>
		<%= link_to 'New Goodbad', new_goodbad_path, class: "btn btn-primary btn-lg" %>
	<% else %>
		<h1>Welcome to my app!</h1> 	
		<p>
			<%= link_to "Log in", new_user_session_path, class: "btn btn-default" %>
			<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %> 
		</p>
	<% end %>
</div>